/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 23.2 and Signal Processing Toolbox 23.2.
 * Generated on: 13-Nov-2023 13:42:03
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 40
 * Stable            : Yes
 * Linear Phase      : Yes (Type 2)
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2023b\extern\include\tmwtypes.h 
 */
const int BL = 40;
const real64_T B[40] = {
  -0.003557610898817, 0.004949949637089, 0.005734626479406,-0.002278951913011,
   0.002919717664348,-0.008909912679504, -0.01581040503946,  0.01603605302542,
    0.01116996679789, 0.002248361007513,   0.0212510373281, -0.03706471387723,
   -0.04691725545537,  0.03709039153797, 0.007513135592429,    0.042519094464,
      0.109045178213,  -0.1738620660493,  -0.2312880917955,   0.2613566043192,
     0.2613566043192,  -0.2312880917955,  -0.1738620660493,    0.109045178213,
      0.042519094464, 0.007513135592429,  0.03709039153797, -0.04691725545537,
   -0.03706471387723,   0.0212510373281, 0.002248361007513,  0.01116996679789,
    0.01603605302542, -0.01581040503946,-0.008909912679504, 0.002919717664348,
  -0.002278951913011, 0.005734626479406, 0.004949949637089,-0.003557610898817
};
